[phases.install]
cmds = [
    "mkdir -p app/Models",
    "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[phases.build]
cmds = [
    "composer dump-autoload --optimize",
    "mkdir -p public/tailwind/src",
    "cp tailwind/src/output.css public/tailwind/src/output.css"
]
